// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4Ypw-ToOSx6bpOR46BilLELHDa6P8wA',
    appId: '1:716318874194:web:6bb7f1abfe2ef4ca711d8b',
    messagingSenderId: '716318874194',
    projectId: 'flutter-e-comm-91dad',
    authDomain: 'flutter-e-comm-91dad.firebaseapp.com',
    storageBucket: 'flutter-e-comm-91dad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvuc2EnRrLeTF2Pst1KwbyIZX7au2UM0',
    appId: '1:716318874194:android:d50f4d4adae8ce3a711d8b',
    messagingSenderId: '716318874194',
    projectId: 'flutter-e-comm-91dad',
    storageBucket: 'flutter-e-comm-91dad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChUw646hMAx_ulfYLCPi-f4G3fdrCavWE',
    appId: '1:716318874194:ios:2c6a54d0945b3598711d8b',
    messagingSenderId: '716318874194',
    projectId: 'flutter-e-comm-91dad',
    storageBucket: 'flutter-e-comm-91dad.firebasestorage.app',
    androidClientId: '716318874194-jecnt45kgpj4a3clatuqq5k9uvo9v3ak.apps.googleusercontent.com',
    iosClientId: '716318874194-cao7h0mbdkit03vkn9pne1vkjun50ue3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}